# Copyright (C) 2021 Filippo Rossi

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers
shoulder_pan_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_pan_joint
  pid: { p: 1000.0, i: 10.0, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
shoulder_lift_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_lift_joint
  pid: { p: 5000.0, i: 100.0, d: 30.0, i_clamp_min: -400.0, i_clamp_max: 400.0 }
elbow_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: elbow_joint
  pid: { p: 5000.0, i: 10.0, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
wrist_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_1_joint
  pid: { p: 200.0, i: 10.0, d: 20.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
wrist_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_2_joint
  pid: { p: 100.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
wrist_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_3_joint
  pid: { p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }

# Gripper controller
gripper_controller:
  type: position_controllers/GripperActionController
  joint: robotiq_2f_left_knuckle_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0
  pid: { p: 40.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
